name: OITC
main: me.despical.oitc.Main
author: Despical
version: ${project.version}
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - Multiverse-Core
  - ProtocolLib
  - Oraxen

permissions:
  oitc.admin.*:
    default: op
    children:
      oitc.admin: true
      oitc.updatenotify: true
      oitc.admin.create: true
      oitc.admin.edit: true
      oitc.admin.reload: true
      oitc.admin.delete: true
      oitc.admin.list: true
      oitc.admin.stop: true
      oitc.admin.forcestart: true
      oitc.admin.addsign: true
      oitc.admin.sign.create: true
      oitc.admin.sign.break: true